import React from 'react';

const toc = [
  { id: 'consent', label: 'Consent' },
  { id: 'nature-and-applicability-of-terms', label: 'NATURE AND APPLICABILITY OF TERMS' },
  { id: 'eligibility', label: 'ELIGIBILITY' },
  { id: 'description-of-services', label: 'DESCRIPTION OF SERVICES' },
  { id: 'payment-on-website-and-app', label: 'PAYMENT ON WEBSITE AND APP' },
  { id: 'cancellation-and-refund-policy', label: 'CANCELLATION AND REFUND POLICY' },
  { id: 'information-uploaded-by-user-on-the-website-app', label: 'INFORMATION UPLOADED BY USER ON THE WEBSITE/ APP' },
  { id: 'privacy-policy', label: 'PRIVACY POLICY' },
  { id: 'disclaimer-of-warranties', label: 'DISCLAIMER OF WARRANTIES' },
  { id: 'limitation-of-liability', label: 'LIMITATION OF LIABILITY' },
  { id: 'use-of-information-on-the-website-social-media-platforms', label: 'USE OF INFORMATION ON THE WEBSITE / SOCIAL MEDIA PLATFORMS' },
  { id: 'no-waiver', label: 'NO WAIVER' },
  { id: 'amendment', label: 'AMENDMENT' },
  { id: 'locations-of-service', label: 'LOCATIONS OF SERVICE' },
  { id: 'term-and-termination', label: 'TERM AND TERMINATION' },
  { id: 'intellectual-property-rights', label: 'INTELLECTUAL PROPERTY RIGHTS' },
  { id: 'force-majeure', label: 'FORCE MAJEURE' },
  { id: 'severability', label: 'SEVERABILITY' },
  { id: 'indenity', label: 'INDEMNITY' },
  { id: 'governing-law', label: 'GOVERNING LAW' },
  { id: 'survival', label: 'SURVIVAL' },
  { id: 'entire-agreement', label: 'ENTIRE AGREEMENT' },
  { id: 'redressal-of-grievance', label: 'REDRESSAL OF GRIEVANCE' },
  { id: 'contact-us', label: 'CONTACT US' },
];

function TermsMain() {
  return (
    <section className="bg-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
          {/* Table of Content */}
          <aside className="md:col-span-1">
            <div className="sticky top-28">
              <h3 className="text-sm font-bold text-[#2d2552] mb-3">Table of Content</h3>
              <nav className="space-y-2">
                {toc.map(item => (
                  <a
                    key={item.id}
                    href={`#${item.id}`}
                    className="block text-sm px-3 py-2 rounded-md text-[#2d2552] hover:bg-gray-100"
                  >
                    {item.label}
                  </a>
                ))}
              </nav>
            </div>
          </aside>

          {/* Main Content */}
          <div className="md:col-span-3">
            {/* Intro */}
            <section aria-labelledby="welcome-title">
              <h2 id="welcome-title" className="text-2xl sm:text-3xl font-extrabold text-[#2d2552]">
                Welcome to Our Terms & Conditions
              </h2>

              <div className="prose max-w-none mt-5 text-gray-700">
                <p>
                  <strong>Medagg Healthcare Private Limited</strong> having its registered office at
                  Phase-1, Sri Harsha 30, villa no 4, Church Rd, Kandhanchavadi, Perungudi, Chennai, Tamil Nadu 600096.
                  (referred to as “we“, “our“, or “us“), operates and manages <strong>www.medagghealthcare.com</strong> and its
                  subdomains (together referred to as “<strong>Website</strong>”).
                </p>
                <p>
                  <strong>Medagg Healthcare</strong>, facilitates and assists users in finding and comparing Interventional
                  Radiologists and health care providers in identified locations (“<strong>service</strong>“) and this service is
                  provided only in good faith. The services of Medagg Healthcare are essentially provided to bridge the
                  information gap between patients and IR doctors.
                </p>
                <p>
                  This document is an electronic record in terms of IT Act, 2000 and rules there under as applicable and the
                  amended provisions pertaining to electronic records in various statutes as amended by the IT Act, 2000. This
                  document is published in accordance with the provisions of Rule 3 (1) of the IT (Intermediaries guidelines)
                  rules, 2011. This electronic record is generated by a computer system and does not require any physical or
                  digital signatures.
                </p>
              </div>
            </section>
 {/* 1. Nature and applicability of terms */}
            <section id="consent" className="mt-10" aria-labelledby="nature-title">
              <h3 id="nature-title" className="text-xl font-bold text-[#2d2552]">
                1. NATURE AND APPLICABILITY OF TERMS
              </h3>

              <div className="mt-4 space-y-6 text-gray-700">
                <p>
                  Please read these terms and conditions (“<strong>Terms</strong>”) before you decide to access the Website or
                  avail the services provided on the Website by Medagg Healthcare. These Terms, along with the Privacy Policy,
                  constitute a legal agreement (“<strong>Agreement</strong>”) between you and Medagg Healthcare in connection
                  with your visit to the Website and your use of the Services.
                </p>
                <p>
                  By downloading or accessing the Website / App to use the Services, you irrevocably accept all the conditions
                  stipulated in this Agreement and the Privacy Policy, as available on the Website, and agree to abide by them.
                  This Agreement supersedes all previous oral and written terms and conditions (if any) communicated to you
                  relating to your use of the Website and the Services. By availing any Service, you signify your acceptance of
                  the terms of this Agreement.
                </p>
              </div>
            </section>

            

            {/* Placeholders for the remaining sections to be filled later, matching TOC */}
            <section id="eligibility" className="mt-10">
              <h3 className="text-xl font-bold text-[#2d2552]">2. Eligibility</h3>
              <div className="mt-3 space-y-4 text-gray-700">
                <p>
                  You must be 18 years of age or older to register, use the Services, or visit or use the Website in any manner. By registering on, visiting, or using the Website, or by accepting this Agreement, you represent and warrant to Medagg Healthcare that you are 18 years of age or older, and that you have the right, authority, and capacity to use the Website and the Services available through it, and to agree to and abide by this Agreement.
                </p>
                <p>
                  By visiting our Website and/or availing our Services on behalf of another individual—such as your child below 18 years of age, a person incapable of providing consent, or an employer—it is deemed that you are the lawful guardian of the child, or are duly authorized by such individual or entity, as the case may be, to accept the Terms of Use on their behalf.
                </p>
              </div>
            </section>

            {/* 3. DESCRIPTION OF SERVICES */}
            <section id="description-of-services" className="mt-10">
              <h3 className="text-xl font-bold text-[#2d2552]">3. DESCRIPTION OF SERVICES</h3>
              <div className="mt-3 space-y-6 text-gray-700">
                <p>
                  <span className="font-semibold">3.1.</span> Medagg Healthcare helps patients understand the need for treatment by providing verified information and assisting them in deciding on the doctor, treatment, and hospital of their choice.
                </p>
                <p>
                  <span className="font-semibold">3.2.</span> After you choose a hospital/doctor, we facilitate consultations and booking appointments. Please note that Medagg is not a provider of any healthcare services, has no responsibility for delivering healthcare services, and does not assume any responsibility beyond facilitation. You agree to assume full responsibility for selecting any hospital/doctor for your treatment. We assume no responsibility or liability for any treatment or healthcare services rendered by any hospital/doctor, or for any malpractice claims, failure to follow adequate standards of care, or any other claims arising directly or indirectly from such advice, treatment, or services.
                </p>
                <div>
                  <p className="font-semibold">3.3. Medagg Healthcare facilitates your treatment(s) at various stages. The Services we provide through our Website (including but not limited to the following) are:</p>
                  <ul className="list-disc ml-5 mt-2 space-y-2">
                    <li>
                      <span className="font-medium">(a) Booking Consultation:</span> We facilitate the booking of preliminary consultations with IR doctors of your choice and book subsequent consultations only upon your request. To avail this Service, you must register on our Website. On successful registration, you will receive confirmation. Upon receiving your request, we will confirm the consultation subject to the availability of the IR doctor during the selected time slot.
                    </li>
                    <li>
                      <span className="font-medium">(b) “Book Your Appointment” Facility:</span> Upon successful submission of a query, we facilitate your receiving a response from the IR doctor via call. Please note that Medagg Healthcare does not provide medical advice or endorse any specific doctor or medical procedure, and we are not responsible for any medical advice given by any doctor.
                    </li>
                    <li>
                      <span className="font-medium">(c) Diagnostic Facility:</span> We facilitate your diagnostic tests as required. Please note that we do not conduct diagnostic tests and are not responsible for any samples collected, tests conducted, or the accuracy, authenticity, or correctness of diagnostic test reports.
                    </li>
                    <li>
                      <span className="font-medium">(d) Post-Operative Care:</span> We facilitate access to post-procedure care facilities of your choice based on your request and/or your doctor’s advice. Please note that we do not refer, recommend, or endorse any post-procedure care providers, organizations, or services.
                    </li>
                  </ul>
                </div>
                <p>
                  <span className="font-semibold">3.4.</span> Medagg Healthcare facilitates contact with doctors and provides information about them and their credentials to help you make informed decisions. We do not, however, recommend any preferred or specific IR doctors for your treatment.
                </p>
                <p>
                  <span className="font-semibold">3.5.</span> Medagg Healthcare agrees to use the Website, the materials provided therein, and avail the Services only for purposes permitted under these Terms of Use, applicable laws, regulations, or generally accepted practices or guidelines in relevant jurisdictions.
                </p>
                <p>
                  <span className="font-semibold">3.6.</span> We reserve the right to accept or refuse to provide any or all Services mentioned in Clause 3.3, as per Clause 4 of these Terms of Use. We may cancel any Services for any reason by informing you at any time before or during the rendering of such Services. We may also cancel your scheduled consultation in case of non-availability of the concerned doctor/surgeon by informing you before the scheduled time. Providing Services remains solely at our discretion and without any liability to you.
                </p>
                <p>
                  <span className="font-semibold">3.7.</span> We reserve the right to add, delete, modify, change, suspend, discontinue, and/or revise the method of providing Services through our Website or otherwise, or to change any features of our Services without prior notice. However, we are not liable for any additions, deletions, modifications, changes, suspensions, discontinuances, or revisions made by surgeons, doctors, medical establishments, clinical labs, diagnostic labs, hospitals, post-procedure care providers, or pharmacies on their respective websites.
                </p>
              </div>
            </section>

            <section id="payment-on-website-and-app" className="mt-10">
              <h3 className="text-xl font-bold text-[#2d2552]">4. PAYMENT ON WEBSITE AND APP</h3>
              <div className="mt-3 space-y-4 text-gray-700">
                <p>
                  The <strong>Medagg Healthcare</strong> Website and App provide you the ability to pay online through a third-party payment gateway for the Services available on the Website or App.
                </p>
                <p>
                  If you choose to pay online, you may be directed to a third-party payment gateway to enable processing of the payment. This transaction will be governed by the terms and conditions and privacy policy of the third-party payment gateway.
                </p>
                <div>
                  <p className="font-semibold">Medagg Healthcare shall not be liable:</p>
                  <ul className="list-disc ml-5 mt-2 space-y-1">
                    <li>(a) if any transaction does not fructify or may not be completed; or</li>
                    <li>(b) for any failure on part of the bank or the credit card or the third-party site or agency to perform any of its obligations; or</li>
                    <li>(c) in respect of any loss or damage arising directly or indirectly from the decline or acceptance of authorization for any transaction, for any reason whatsoever.</li>
                  </ul>
                </div>
              </div>
            </section>

            {/* 5. CANCELLATION AND REFUND POLICY */}
            <section id="cancellation-and-refund-policy" className="mt-10">
              <h3 className="text-xl font-bold text-[#2d2552]">5. CANCELLATION AND REFUND POLICY</h3>
              <div className="mt-3 space-y-4 text-gray-700">
                <p>
                  The cancellation and refund policy is only applicable for booking appointments.
                </p>
                <div>
                  <p className="font-semibold">In case cancellation is initiated by user:</p>
                  <ul className="list-disc ml-5 mt-2 space-y-1">
                    <li>
                      <span className="font-medium">Before Scheduled Appointment Time:</span> Facility of change in date and timing will be provided, but no refund is applicable.
                    </li>
                    <li>
                      <span className="font-medium">After Scheduled Appointment Time:</span> Neither consultation fees nor reschedule will be entertained.
                    </li>
                  </ul>
                </div>
                <p>
                  In case cancellation is initiated by a relevant hospital due to unavailability of doctor, 100% of consultation fees and convenience fees will be refunded to the end user.
                </p>
                <p>
                  At the time of cancellation, the amount will be refunded via the same source of payment and will be subject to the payment terms of the source only. Amount will be refunded within 7 working days.
                </p>
              </div>
            </section>

            <section id="information-uploaded-by-user-on-the-website-app" className="mt-10">
              <h3 className="text-xl font-bold text-[#2d2552]">6. INFORMATION UPLOADED BY USER ON THE WEBSITE/ APP</h3>
              <div className="mt-3 space-y-4 text-gray-700">
                <p>
                  You understand that you may have the option of sharing your health / medical information with us in order to enable our consultants to peruse your previous medical history before consultation. While <strong>Medagg Healthcare</strong> takes utmost care with respect to the security of the information you decide to share, you understand that any information that you disclose and share with us is at your own risk.
                </p>
                <p>
                  By uploading / sharing / disclosing your medical information on the Website / App, you hereby give your consent to the Website / App to store such health / medical information on Medagg Healthcare’s servers. <strong>Medagg Healthcare</strong> will retain such medical / health information you share as long as it is needed to fully fulfill the service you seek to avail on the Website / App. If you delete your account, <strong>Medagg Healthcare</strong> will delete such medical / health information. But please note:
                </p>
                <ul className="list-disc ml-5 mt-1 space-y-1">
                  <li>There might be some latency in deleting this information from our servers and backup storage.</li>
                  <li>We may retain this information if necessary to comply with our legal obligations, resolve disputes, or enforce our agreements.</li>
                </ul>
              </div>
            </section>

            {/* 7. PRIVACY POLICY */}
            <section id="privacy-policy" className="mt-10">
              <h3 className="text-xl font-bold text-[#2d2552]">7. PRIVACY POLICY</h3>
              <div className="mt-3 space-y-4 text-gray-700">
                <p>
                  The Privacy Policy sets out,
                </p>
                <div>
                  <p className="font-semibold">7.1.</p>
                  <p className="mt-1">
                    The User is expected to read and understand the Privacy Policy, so as to ensure that he or she has the knowledge of, inter-alia:
                  </p>
                  <ul className="list-disc ml-5 mt-2 space-y-1">
                    <li>the fact that certain information is being collected;</li>
                    <li>the purpose for which the information is being collected;</li>
                    <li>the intended recipients of the information;</li>
                    <li>the nature of collection and retention of the information; and</li>
                    <li>the various rights available to such Users in respect of such information.</li>
                  </ul>
                </div>
                <p>
                  <span className="font-semibold">7.2.</span> <strong>Medagg Healthcare</strong> shall not be responsible in any manner for the authenticity of the personal information or sensitive personal data or information supplied by the User to Medagg Healthcare or to any other person acting on behalf of Medagg Healthcare.
                </p>
                <p>
                  <span className="font-semibold">7.3.</span> If a User provides any information that is untrue, inaccurate, not current or incomplete (or becomes untrue, inaccurate, not current or incomplete), or <strong>Medagg Healthcare</strong> has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, <strong>Medagg Healthcare</strong> has the right to discontinue the Services to the User at its sole discretion.
                </p>
                <p>
                  <span className="font-semibold">7.4.</span> <strong>Medagg Healthcare</strong> may use such information collected from the Users from time to time for the purposes of debugging customer support related issues.
                </p>
                <p>
                  <span className="font-semibold">7.5.</span> It is your responsibility to keep your email address and mobile phone number up-to-date with us so that we can communicate with you to provide Services. By providing your information and registering with, you agree to receive communications from us via email, telephone, mobile short message service (SMS) and messaging apps (including but not limited to WhatsApp). If you, at any time, wish to discontinue receiving communications from us, you agree to notify us by email.
                </p>
                <div>
                  <p className="font-semibold">7.6. <span className="font-normal">Medagg Healthcare reserve the right to refuse access to our Website and/or refuse to provide you with our Services, if:</span></p>
                  <ul className="list-disc ml-5 mt-2 space-y-1">
                    <li>(a) You misbehave with any or all of the employees/staff/authorized personal of “Medagg”.</li>
                    <li>(b) You misrepresent that you are the lawful guardian of a child below the age of 18 years and or you are authorized on behalf of any person not capable of providing consent or an employer to avail our Services and/or access our Website;</li>
                    <li>(d) You interfere with the operation and management of “Medagg” or any of the authorized healthcare providers including but not limited to contracted hospitals or clinical labs or diagnostic labs or post-operative care operators.</li>
                  </ul>
                </div>
              </div>
            </section>

            {/* 8. DISCLAIMER OF WARRANTIES */}
            <section id="disclaimer-of-warranties" className="mt-10">
              <h3 className="text-xl font-bold text-[#2d2552]">8. DISCLAIMER OF WARRANTIES</h3>
              <div className="mt-3 space-y-4 text-gray-700">
                <p>
                  <span className="font-semibold">8.1.</span> You are 18 years of age or older and that your use of the App shall not violate any applicable law or regulation.
                </p>
                <p>
                  <span className="font-semibold">8.2.</span> All information you submit is truthful and accurate and that you agree to maintain the accuracy of such information.
                </p>
                <p>
                  <span className="font-semibold">8.3.</span> Your access on the website / app is solely for your personal and non-commercial use. Any use of this app or its content other than for personal purposes is prohibited. You may not modify, decompile, reverse engineer, or disassemble any content of the website, or remove any copyright, trademark registration, or other proprietary notices from the app and use it for any commercial or harmful purpose.
                </p>
                <p>
                  <span className="font-semibold">8.4.</span> All information and Services included on or otherwise made available to you through this Website are provided by us on an “as is” basis, either expressed or implied, we specifically disclaim warranties of any kind to the extent allowed by the applicable law. You expressly agree that your use of this Website and/or our Services is at your sole risk.
                </p>
                <p>
                  <span className="font-semibold">8.5.</span> We cannot guarantee the adequacy or completeness of the information with regard to the service provider as listed on our website. We do not warrant or endorse the effectiveness, quality, or safety of the Services available on our Website.
                </p>
                <p>
                  <span className="font-semibold">8.6.</span> We assume no responsibility for any damages or viruses that may infect your computer equipment or other property on account of your access to, use of, or browsing this Website.
                </p>
                <p>
                  <span className="font-semibold">8.7.</span> You will not engage in any form of antisocial, disrupting, or destructive acts, including “flaming”, “spamming”, “flooding”, “trolling”, “phishing” and “griefing” as those terms are commonly understood and used on the Internet.
                </p>
                <p>
                  <span className="font-semibold">8.8.</span> You will not delete or modify any content of the app and/or services, including but not limited to, legal notices, disclaimers or proprietary notices such as copyright or trademark symbols, logos, that you do not own or have express permission to modify.
                </p>
              </div>
            </section>

            {/* 9. LIMITATION OF LIABILITY */}
            <section id="limitation-of-liability" className="mt-10">
              <h3 className="text-xl font-bold text-[#2d2552]">9. LIMITATION OF LIABILITY</h3>
              <div className="mt-3 space-y-4 text-gray-700">
                <p>
                  <span className="font-semibold">9.1.</span> <strong>Medagg Healthcare</strong> has exerted reasonable efforts to ensure that all information published on the Website is accurate at the time of posting; however, there may be errors in such information for which we shall have no liability. We reserve the right to remove, modify, amend or alter any of the information contained on the Website at our sole discretion.
                </p>
                <p>
                  <span className="font-semibold">9.2.</span> <strong>Medagg Healthcare</strong> may let you view our information and communicate with us through third party social media services. We explicitly disclaim any responsibility for the terms of use and privacy policies that govern these third-party websites, which are in no way associated with us.
                </p>
                <p>
                  <span className="font-semibold">9.3.</span> <strong>Medagg Healthcare</strong> reserves the right to modify or withdraw any part of the Website, any of its content, and/or any Services at any time without any notice.
                </p>
                <p>
                  <span className="font-semibold">9.4.</span> <strong>Medagg Healthcare</strong> shall not be responsible or liable in any manner to you for any losses, damages, injuries, or expenses incurred by you as a result of any disclosures made by us, where you have consented to the making of such disclosures by us. You shall not hold us responsible or liable in any way for any disclosures by us since it is in compliance with applicable laws.
                </p>
                <p>
                  <span className="font-semibold">9.5.</span> Doctors/surgeons or other healthcare professionals, hospitals, diagnostic labs, clinical labs, post-operative care providers and pharmacies are responsible for complying with applicable laws and with regulatory and applicable requirements for malpractice and liability. All interactions between you and doctors/surgeons and other healthcare professionals are at your own risk.
                </p>
                <p>
                  <span className="font-semibold">9.6.</span> Further, individual contracts exists between the doctor/surgeon or other healthcare providers and you, between the hospital and you, between the post-operative care provider and you, between the diagnostic lab or clinical lab and you, and pharmacy and you, and as such any breach of any of these contracts and thus, any claim arising from such breach is the subject matter of the doctor/surgeon or other healthcare provider or hospital or post-operative care provider or diagnostic/clinical lab or pharmacy and you alone, and we are in no way a party to such breach / mishap / missed services caused due to third party service provider nor involved in any suit including but not limited to any claim or negligence or damages arising from the same breach.
                </p>
              </div>
            </section>

            {/* 10. USE OF INFORMATION ON THE WEBSITE / SOCIAL MEDIA PLATFORMS */}
            <section id="use-of-information-on-the-website-social-media-platforms" className="mt-10">
              <h3 className="text-xl font-bold text-[#2d2552]">10. USE OF INFORMATION ON THE WEBSITE / SOCIAL MEDIA PLATFORMS</h3>
              <div className="mt-3 space-y-4 text-gray-700">
                <p>
                  <strong>Medagg Healthcare</strong> collects, directly or indirectly, and displays on the Website, relevant information regarding the profile and practice of the Practitioners listed on the Website, such as their specialization, qualification, fees, location, visiting hours, and similar details. <strong>Medagg Healthcare</strong> takes reasonable efforts to ensure that such information is updated at frequent intervals. <strong>Medagg Healthcare</strong> cannot be held liable for any inaccuracies or incompleteness represented from it, despite such reasonable efforts.
                </p>
                <p>
                  Any information, views, opinions and/or suggestions, transmitted/endorsed/uploaded on the website, via e-mail, phone, social media platforms, mobile not be construed as medical advice or treatment for specific medical conditions and we encourage you to consult and act upon all your medical issues as per the advice of a medical practitioner of your choice. Your submission of questions, reviews or testimonials about our Services does not in any manner constitute a professional relationship between us.
                </p>
              </div>
            </section>

            {/* 11. NO WAIVER */}
            <section id="no-waiver" className="mt-10">
              <h3 className="text-xl font-bold text-[#2d2552]">11. NO WAIVER</h3>
              <div className="mt-3 space-y-4 text-gray-700">
                <p>
                  The failure of Medagg Healthcare to enforce any right or provision of these Terms will not constitute a waiver of future enforcement of that right or provision. The waiver of any such right or provision will be effective only if in writing and signed by a duly authorized representative of Medagg Healthcare.
                </p>
              </div>
            </section>

            {/* 12. AMENDMENT */}
            <section id="amendment" className="mt-10">
              <h3 className="text-xl font-bold text-[#2d2552]">12. AMENDMENT</h3>
              <div className="mt-3 space-y-4 text-gray-700">
                <p>
                  We reserve the right to modify or terminate any portion of the Agreement for any reason and at any time, and such modifications shall be informed to you in writing. You should read the Agreement at regular intervals. Your use of the Website following any such modification constitutes your agreement to follow and be bound by the Agreement so modified.
                </p>
                <p>
                  You acknowledge that you will be bound by this Agreement for availing any of the Services offered by us. If you do not agree with any part of the Agreement, please do not use the Website or avail any Services.
                </p>
              </div>
            </section>

            {/* 13. LOCATIONS OF SERVICE */}
            <section id="locations-of-service" className="mt-10">
              <h3 className="text-xl font-bold text-[#2d2552]">13. LOCATIONS OF SERVICE</h3>
              <div className="mt-3 space-y-4 text-gray-700">
                <p>
                  Currently, the Services are available only in some cities (Chennai, Madurai, Coimbatore, Trichy, Salem, Calicut, Trivandrum, Bangalore, Hyderabad, Pune, Bhubaneswar, Ahmedabad, Pondicherry, Mangalore, Goa, Perinthalmanna, Kolkata, Delhi, Jaipur). We shall update the Website and/or Terms of Use in case of any addition or deletion of our operating locations.
                </p>
              </div>
            </section>

            {/* 14. TERM AND TERMINATION */}
            <section id="term-and-termination" className="mt-10">
              <h3 className="text-xl font-bold text-[#2d2552]">14. TERM AND TERMINATION</h3>
              <div className="mt-3 space-y-4 text-gray-700">
                <p>
                  These Terms are effective and binding on you when you begin using the Services, and will remain in effect for as long as you continue to use the Services or until they are amended or modified by Medagg Healthcare, or terminated by Medagg Healthcare according to this section. Medagg Healthcare may immediately, without notice, terminate these Terms and disable your access to the services if Medagg Healthcare, in its sole discretion, determines that
                </p>
                <ul className="list-disc ml-5 space-y-1">
                  <li>1. if the user is under the age of 18 years.</li>
                  <li>2. You have provided inaccurate, fraudulent, outdated or incomplete information during account registration.</li>
                  <li>3. You have violated applicable laws, regulations or third-party rights; or</li>
                  <li>4. A third-party reports violation of any of its right as a result of your use of the Services;</li>
                  <li>5. Medagg Healthcare is unable to verify or authenticate any information provided to Medagg Healthcare by a User;</li>
                  <li>6. Medagg Healthcare has reasonable grounds for suspecting any illegal, fraudulent or abusive activity on part of such User; or</li>
                  <li>7. Medagg Healthcare believes in its sole discretion that User’s actions may cause legal liability for such User, other Users or for Medagg Healthcare or its Partners or are contrary to the interests of the Website.</li>
                  <li>8. Medagg Healthcare believes in good faith that such action is reasonably necessary to protect the safety or property of other users, Medagg Healthcare, or third parties. Medagg Healthcare may, at any time, and for any reason or no reason whatsoever, choose to cease providing the Services.</li>
                </ul>
              </div>
            </section>

            {/* 15. INTELLECTUAL PROPERTY RIGHTS */}
            <section id="intellectual-property-rights" className="mt-10">
              <h3 className="text-xl font-bold text-[#2d2552]">15. INTELLECTUAL PROPERTY RIGHTS</h3>
              <div className="mt-3 space-y-4 text-gray-700">
                <p>
                  All the intellectual property used on the Website shall remain our exclusive property. The materials on the Website or otherwise may not be modified, copied, reproduced, distributed, republished, downloaded, displayed, sold, compiled, posted or transmitted in any form or by any means, including but not limited to, electronic, mechanical, photocopying, recording or other means.
                </p>
              </div>
            </section>

            {/* 16. FORCE MAJEURE */}
            <section id="force-majeure" className="mt-10">
              <h3 className="text-xl font-bold text-[#2d2552]">16. FORCE MAJEURE</h3>
              <div className="mt-3 space-y-4 text-gray-700">
                <p>
                  A Party shall be not be considered in breach of or in default under this Agreement on account of, and shall not be liable to the other Party for, any delay or failure to perform its obligations hereunder by reason of fire, earthquake, flood, explosion, strike, riot, war, terrorism, or similar event beyond that Party’s reasonable control (each a “Force Majeure Event”);
                  <span className="font-semibold"> provided, however,</span> if a Force Majeure Event occurs, the affected Party shall, as soon as practicable:
                </p>
                <ul className="list-disc ml-5 space-y-1">
                  <li>notify the other Party of the Force Majeure Event and its impact on performance under this Agreement; and</li>
                  <li>use reasonable efforts to resolve any issues resulting from the Force Majeure Event and perform its obligations hereunder.</li>
                </ul>
              </div>
            </section>
            {/* 17. SEVERABILITY */}
            <section id="severability" className="mt-10">
              <h3 className="text-xl font-bold text-[#2d2552]">17. SEVERABILITY</h3>
              <div className="mt-3 space-y-4 text-gray-700">
                <p>
                  If any provision of the Agreement is held by a court of competent jurisdiction or arbitral tribunal to be unenforceable under applicable law, then such provision shall be excluded from this Agreement and the remainder of the Agreement shall be interpreted as if such provision were so excluded and shall be enforceable in accordance with its terms; provided however that, in such event, the Agreement shall be interpreted so as to give effect, to the greatest extent consistent with and permitted by applicable law, to the meaning and intention of the excluded provision as determined by such court of competent jurisdiction or arbitral tribunal.
                </p>
              </div>
            </section>

            {/* 18. INDEMNITY */}
            <section id="indenity" className="mt-10">
              <h3 className="text-xl font-bold text-[#2d2552]">18. INDEMNITY</h3>
              <div className="mt-3 space-y-4 text-gray-700">
                <p>
                  User agrees to indemnify and hold harmless Medagg Healthcare, its affiliates, officers, directors, employees, consultants, licensors, agents, representatives and Partners from any and all third party claims, losses, liability, damages, and/or costs (including reasonable attorney fees and costs) arising from User’s access to or use of Service, violation of this Agreement, or infringement, or infringement by any other User of his/her/its account, of any intellectual property or other right of any person or entity.
                </p>
              </div>
            </section>

            {/* 19. GOVERNING LAW */}
            <section id="governing-law" className="mt-10">
              <h3 className="text-xl font-bold text-[#2d2552]">19. GOVERNING LAW</h3>
              <div className="mt-3 space-y-4 text-gray-700">
                <p>
                  You agree that this Agreement and any contractual obligation between the Medagg Healthcare and User will be governed by the laws of India.
                </p>
                <p>
                  Subject to the Paragraph above, the courts at Chennai shall have exclusive jurisdiction over any disputes arising out of or in relation to this Agreement, your use of the Website or the Services or the information to which it gives access.
                </p>
              </div>
            </section>

            {/* 20. SURVIVAL */}
            <section id="survival" className="mt-10">
              <h3 className="text-xl font-bold text-[#2d2552]">20. SURVIVAL</h3>
              <div className="mt-3 space-y-4 text-gray-700">
                <p>
                  Even after termination, certain obligations mentioned under Disclaimer of Warranties and Limitation of Liability, Indemnity, Intellectual Property and Dispute Resolution will continue and survive termination.
                </p>
              </div>
            </section>

            {/* 21. ENTIRE AGREEMENT */}
            <section id="entire-agreement" className="mt-10">
              <h3 className="text-xl font-bold text-[#2d2552]">21. ENTIRE AGREEMENT</h3>
              <div className="mt-3 space-y-4 text-gray-700">
                <p>
                  This Agreement, constitutes the final, complete, and exclusive statement of the agreement of the Parties with respect to the subject matter hereof, and supersedes any and all other prior and contemporaneous agreements and understandings, both written and oral, between the Parties.
                </p>
              </div>
            </section>

            {/* 22. REDRESSAL OF GRIEVANCE */}
            <section id="redressal-of-grievance" className="mt-10">
              <h3 className="text-xl font-bold text-[#2d2552]">22. REDRESSAL OF GRIEVANCE</h3>
              <div className="mt-3 space-y-4 text-gray-700">
                <p>
                  This Agreement defines the terms and conditions under which you are allowed to use the Website and describes the manner in which we shall treat your account while you are registered as a member with us.
                </p>
                <p>
                  If you have any grievance, queries, claims, complaints about any part of the Agreement, feel free to contact us at <a href="mailto:contact@medagghealthcare.com" className="text-[#2d2552] underline">contact@medagghealthcare.com</a>.
                </p>
                <p>
                  The same shall be resolved within a period of 30 days from the date of such receipt.
                </p>
              </div>
            </section>

            {/* 23. CONTACT US */}
            <section id="contact-us" className="mt-10">
              <h3 className="text-xl font-bold text-[#2d2552]">23. CONTACT US</h3>
              <div className="mt-3 space-y-4 text-gray-700">
                <p>
                  If you have questions about this agreement, or any concerns, please feel free to reach us via <a href="mailto:contact@medagghealthcare.com" className="text-[#2d2552] underline">contact@medagghealthcare.com</a>.
                </p>
              </div>
            </section>

            
            
            
          </div>
        </div>
      </div>
    </section>
  );
}

export default TermsMain;